//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILCookTKIDSInboundFileJob.Entities
{
  using System.Xml.Serialization;
  using Tyler.Odyssey.API.Shared;

  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Message",IsNullable = false)]
  public partial class DeletePartyDetailsEntity : BaseGeneratedAPIEntity
  {

    private string partyIDField;

    private DELETEPARTYDETAILSDELETE deleteField;

    private LOCALDELETEPARTYDETAILS messageTypeField;

    private BASEREQUIREDZERO nodeIDField;

    private string referenceNumberField;

    private string userIDField;

    private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string PartyID
    {
      get
      {
        return this.partyIDField;
      }
      set
      {
        this.partyIDField = value;
      }
    }

    /// <remarks/>
    public DELETEPARTYDETAILSDELETE Delete
    {
      get
      {
        return this.deleteField;
      }
      set
      {
        this.deleteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LOCALDELETEPARTYDETAILS MessageType
    {
      get
      {
        return this.messageTypeField;
      }
      set
      {
        this.messageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BASEREQUIREDZERO NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferenceNumber
    {
      get
      {
        return this.referenceNumberField;
      }
      set
      {
        this.referenceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DELETEPARTYDETAILS.DELETE")]
  public partial class DELETEPARTYDETAILSDELETE
  {

    private string nameAliasesField;

    private string dateOfBirthsField;

    private string dateOfDeathField;

    private string weightField;

    private string genderField;

    private string hairColorField;

    private string eyeColorField;

    private string driversLicensesField;

    private string fBINumbersField;

    private string sONumbersField;

    private string otherAgencyNumbersField;

    private string emailsField;

    private string phonesField;

    private string languagesField;

    private string stateIDsField;

    private string legacyIDsField;

    /// <remarks/>
    public string NameAliases
    {
      get
      {
        return this.nameAliasesField;
      }
      set
      {
        this.nameAliasesField = value;
      }
    }

    /// <remarks/>
    public string DateOfBirths
    {
      get
      {
        return this.dateOfBirthsField;
      }
      set
      {
        this.dateOfBirthsField = value;
      }
    }

    /// <remarks/>
    public string DateOfDeath
    {
      get
      {
        return this.dateOfDeathField;
      }
      set
      {
        this.dateOfDeathField = value;
      }
    }

    /// <remarks/>
    public string Weight
    {
      get
      {
        return this.weightField;
      }
      set
      {
        this.weightField = value;
      }
    }

    /// <remarks/>
    public string Gender
    {
      get
      {
        return this.genderField;
      }
      set
      {
        this.genderField = value;
      }
    }

    /// <remarks/>
    public string HairColor
    {
      get
      {
        return this.hairColorField;
      }
      set
      {
        this.hairColorField = value;
      }
    }

    /// <remarks/>
    public string EyeColor
    {
      get
      {
        return this.eyeColorField;
      }
      set
      {
        this.eyeColorField = value;
      }
    }

    /// <remarks/>
    public string DriversLicenses
    {
      get
      {
        return this.driversLicensesField;
      }
      set
      {
        this.driversLicensesField = value;
      }
    }

    /// <remarks/>
    public string FBINumbers
    {
      get
      {
        return this.fBINumbersField;
      }
      set
      {
        this.fBINumbersField = value;
      }
    }

    /// <remarks/>
    public string SONumbers
    {
      get
      {
        return this.sONumbersField;
      }
      set
      {
        this.sONumbersField = value;
      }
    }

    /// <remarks/>
    public string OtherAgencyNumbers
    {
      get
      {
        return this.otherAgencyNumbersField;
      }
      set
      {
        this.otherAgencyNumbersField = value;
      }
    }

    /// <remarks/>
    public string Emails
    {
      get
      {
        return this.emailsField;
      }
      set
      {
        this.emailsField = value;
      }
    }

    /// <remarks/>
    public string Phones
    {
      get
      {
        return this.phonesField;
      }
      set
      {
        this.phonesField = value;
      }
    }

    /// <remarks/>
    public string Languages
    {
      get
      {
        return this.languagesField;
      }
      set
      {
        this.languagesField = value;
      }
    }

    /// <remarks/>
    public string StateIDs
    {
      get
      {
        return this.stateIDsField;
      }
      set
      {
        this.stateIDsField = value;
      }
    }

    /// <remarks/>
    public string LegacyIDs
    {
      get
      {
        return this.legacyIDsField;
      }
      set
      {
        this.legacyIDsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOCAL.DELETEPARTYDETAILS")]
  public enum LOCALDELETEPARTYDETAILS
  {

    /// <remarks/>
    DeletePartyDetails,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.REQUIREDZERO")]
  public enum BASEREQUIREDZERO
  {

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
  }
}