//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILCookTKIDSInboundFileJob.Entities
{
  using System.Xml.Serialization;
  using Tyler.Odyssey.API.Shared;

  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Result", IsNullable = false)]
  public partial class LoadCaseResult : BaseGeneratedAPIEntity
  {

    private LoadCaseCase caseField;

    /// <remarks/>
    public LoadCaseCase Case
    {
      get
      {
        return this.caseField;
      }
      set
      {
        this.caseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Case")]
  public partial class LoadCaseCase
  {

    private string caseNumberField;

    private string caseIDField;

    private string styleField;

    private string nodeIDField;

    private string categoryField;

    private string typeField;

    private string securityGroupField;

    private string judgeField;

    private string fileDateField;

    private LoadCaseCaseStatus[] caseStatusesField;

    private LoadCaseCaseParties casePartiesField;

    private LoadCaseCaseEvent[] eventsField;

    private LoadCaseCharge[] chargesField;

    private LoadCaseCauseOfAction[] causesOfActionField;

    private LoadCaseCaseCrossReference[] caseCrossReferencesField;

    private LoadCaseCaseFlag[] caseFlagsField;

    private LoadCaseInterimPlacement[] interimPlacementsField;

    /// <remarks/>
    public string CaseNumber
    {
      get
      {
        return this.caseNumberField;
      }
      set
      {
        this.caseNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CaseID
    {
      get
      {
        return this.caseIDField;
      }
      set
      {
        this.caseIDField = value;
      }
    }

    /// <remarks/>
    public string Style
    {
      get
      {
        return this.styleField;
      }
      set
      {
        this.styleField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    public string Category
    {
      get
      {
        return this.categoryField;
      }
      set
      {
        this.categoryField = value;
      }
    }

    /// <remarks/>
    public string Type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    public string SecurityGroup
    {
      get
      {
        return this.securityGroupField;
      }
      set
      {
        this.securityGroupField = value;
      }
    }

    /// <remarks/>
    public string Judge
    {
      get
      {
        return this.judgeField;
      }
      set
      {
        this.judgeField = value;
      }
    }

    /// <remarks/>
    public string FileDate
    {
      get
      {
        return this.fileDateField;
      }
      set
      {
        this.fileDateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CaseStatus", IsNullable = false)]
    public LoadCaseCaseStatus[] CaseStatuses
    {
      get
      {
        return this.caseStatusesField;
      }
      set
      {
        this.caseStatusesField = value;
      }
    }

    /// <remarks/>
    public LoadCaseCaseParties CaseParties
    {
      get
      {
        return this.casePartiesField;
      }
      set
      {
        this.casePartiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable = false)]
    public LoadCaseCaseEvent[] Events
    {
      get
      {
        return this.eventsField;
      }
      set
      {
        this.eventsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Charge", IsNullable = false)]
    public LoadCaseCharge[] Charges
    {
      get
      {
        return this.chargesField;
      }
      set
      {
        this.chargesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CauseOfAction", IsNullable = false)]
    public LoadCaseCauseOfAction[] CausesOfAction
    {
      get
      {
        return this.causesOfActionField;
      }
      set
      {
        this.causesOfActionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CaseCrossReference", IsNullable = false)]
    public LoadCaseCaseCrossReference[] CaseCrossReferences
    {
      get
      {
        return this.caseCrossReferencesField;
      }
      set
      {
        this.caseCrossReferencesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CaseFlag", IsNullable = false)]
    public LoadCaseCaseFlag[] CaseFlags
    {
      get
      {
        return this.caseFlagsField;
      }
      set
      {
        this.caseFlagsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("InterimPlacement", IsNullable = false)]
    public LoadCaseInterimPlacement[] InterimPlacements
    {
      get
      {
        return this.interimPlacementsField;
      }
      set
      {
        this.interimPlacementsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseStatus")]
  public partial class LoadCaseCaseStatus
  {

    private string statusTypeField;

    private string dateField;

    private string commentField;

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private bool isCurrentFieldSpecified;

    private BASEREQUIREDTEXTBOOL makesCaseActiveField;

    private bool makesCaseActiveFieldSpecified;

    /// <remarks/>
    public string StatusType
    {
      get
      {
        return this.statusTypeField;
      }
      set
      {
        this.statusTypeField = value;
      }
    }

    /// <remarks/>
    public string Date
    {
      get
      {
        return this.dateField;
      }
      set
      {
        this.dateField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsCurrentSpecified
    {
      get
      {
        return this.isCurrentFieldSpecified;
      }
      set
      {
        this.isCurrentFieldSpecified = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL MakesCaseActive
    {
      get
      {
        return this.makesCaseActiveField;
      }
      set
      {
        this.makesCaseActiveField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MakesCaseActiveSpecified
    {
      get
      {
        return this.makesCaseActiveFieldSpecified;
      }
      set
      {
        this.makesCaseActiveFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.REQUIREDTEXTBOOL")]
  public enum BASEREQUIREDTEXTBOOL
  {

    /// <remarks/>
    @true,

    /// <remarks/>
    @false,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.LOCATIONPARTY")]
  public partial class LoadCaseLOCATIONPARTY
  {

    private string partyIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string PartyID
    {
      get
      {
        return this.partyIDField;
      }
      set
      {
        this.partyIDField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.LOCATIONDESCRIPTION")]
  public partial class LoadCaseLOCATIONDESCRIPTION
  {

    private string descriptionField;

    /// <remarks/>
    public string Description
    {
      get
      {
        return this.descriptionField;
      }
      set
      {
        this.descriptionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.LOCATIONAGENCY")]
  public partial class LoadCaseLOCATIONAGENCY
  {

    private string agencyField;

    /// <remarks/>
    public string Agency
    {
      get
      {
        return this.agencyField;
      }
      set
      {
        this.agencyField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.LOCATION")]
  public partial class LoadCaseLOCATION
  {

    private LoadCaseLOCATIONAGENCY locationAgencyField;

    private LoadCaseLOCATIONDESCRIPTION locationDescriptionField;

    private LoadCaseLOCATIONPARTY locationPartyField;

    /// <remarks/>
    public LoadCaseLOCATIONAGENCY LocationAgency
    {
      get
      {
        return this.locationAgencyField;
      }
      set
      {
        this.locationAgencyField = value;
      }
    }

    /// <remarks/>
    public LoadCaseLOCATIONDESCRIPTION LocationDescription
    {
      get
      {
        return this.locationDescriptionField;
      }
      set
      {
        this.locationDescriptionField = value;
      }
    }

    /// <remarks/>
    public LoadCaseLOCATIONPARTY LocationParty
    {
      get
      {
        return this.locationPartyField;
      }
      set
      {
        this.locationPartyField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.InterimPlacement")]
  public partial class LoadCaseInterimPlacement
  {

    private string interimPlacementIDField;

    private string partyIDField;

    private string placementTypeField;

    private LoadCaseLOCATION locationField;

    private string orderDateField;

    private string startDateField;

    private string endDateField;

    private string commentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string InterimPlacementID
    {
      get
      {
        return this.interimPlacementIDField;
      }
      set
      {
        this.interimPlacementIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string PartyID
    {
      get
      {
        return this.partyIDField;
      }
      set
      {
        this.partyIDField = value;
      }
    }

    /// <remarks/>
    public string PlacementType
    {
      get
      {
        return this.placementTypeField;
      }
      set
      {
        this.placementTypeField = value;
      }
    }

    /// <remarks/>
    public LoadCaseLOCATION Location
    {
      get
      {
        return this.locationField;
      }
      set
      {
        this.locationField = value;
      }
    }

    /// <remarks/>
    public string OrderDate
    {
      get
      {
        return this.orderDateField;
      }
      set
      {
        this.orderDateField = value;
      }
    }

    /// <remarks/>
    public string StartDate
    {
      get
      {
        return this.startDateField;
      }
      set
      {
        this.startDateField = value;
      }
    }

    /// <remarks/>
    public string EndDate
    {
      get
      {
        return this.endDateField;
      }
      set
      {
        this.endDateField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseFlag")]
  public partial class LoadCaseCaseFlag
  {

    private string flagTypeField;

    private string commentField;

    /// <remarks/>
    public string FlagType
    {
      get
      {
        return this.flagTypeField;
      }
      set
      {
        this.flagTypeField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseCrossReference")]
  public partial class LoadCaseCaseCrossReference
  {

    private string crossReferenceNumberField;

    private string crossReferenceNumberTypeField;

    /// <remarks/>
    public string CrossReferenceNumber
    {
      get
      {
        return this.crossReferenceNumberField;
      }
      set
      {
        this.crossReferenceNumberField = value;
      }
    }

    /// <remarks/>
    public string CrossReferenceNumberType
    {
      get
      {
        return this.crossReferenceNumberTypeField;
      }
      set
      {
        this.crossReferenceNumberTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.RemedySought")]
  public partial class LoadCaseRemedySought
  {

    private string remedyTypeField;

    private decimal remedyAmountField;

    private bool remedyAmountFieldSpecified;

    private string remedyCommentField;

    /// <remarks/>
    public string RemedyType
    {
      get
      {
        return this.remedyTypeField;
      }
      set
      {
        this.remedyTypeField = value;
      }
    }

    /// <remarks/>
    public decimal RemedyAmount
    {
      get
      {
        return this.remedyAmountField;
      }
      set
      {
        this.remedyAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RemedyAmountSpecified
    {
      get
      {
        return this.remedyAmountFieldSpecified;
      }
      set
      {
        this.remedyAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string RemedyComment
    {
      get
      {
        return this.remedyCommentField;
      }
      set
      {
        this.remedyCommentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CauseOfAction")]
  public partial class LoadCaseCauseOfAction
  {

    private string causeOfActionIDField;

    private string actionTypeField;

    private string causeCodeField;

    private string parcelNumberField;

    private string fileDateField;

    private string descriptionField;

    private LoadCaseRemedySought[] remediesSoughtField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CauseOfActionID
    {
      get
      {
        return this.causeOfActionIDField;
      }
      set
      {
        this.causeOfActionIDField = value;
      }
    }

    /// <remarks/>
    public string ActionType
    {
      get
      {
        return this.actionTypeField;
      }
      set
      {
        this.actionTypeField = value;
      }
    }

    /// <remarks/>
    public string CauseCode
    {
      get
      {
        return this.causeCodeField;
      }
      set
      {
        this.causeCodeField = value;
      }
    }

    /// <remarks/>
    public string ParcelNumber
    {
      get
      {
        return this.parcelNumberField;
      }
      set
      {
        this.parcelNumberField = value;
      }
    }

    /// <remarks/>
    public string FileDate
    {
      get
      {
        return this.fileDateField;
      }
      set
      {
        this.fileDateField = value;
      }
    }

    /// <remarks/>
    public string Description
    {
      get
      {
        return this.descriptionField;
      }
      set
      {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RemedySought", IsNullable = false)]
    public LoadCaseRemedySought[] RemediesSought
    {
      get
      {
        return this.remediesSoughtField;
      }
      set
      {
        this.remediesSoughtField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CitiationFiling")]
  public partial class LoadCaseCitiationFiling
  {

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private string numberField;

    private string citationNumberField;

    private string citationIDField;

    private string jurisdictionField;

    private decimal fineAmountField;

    private bool fineAmountFieldSpecified;

    private LoadCaseBond bondField;

    private LoadCaseOffense offenseField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string Number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    public string CitationNumber
    {
      get
      {
        return this.citationNumberField;
      }
      set
      {
        this.citationNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CitationID
    {
      get
      {
        return this.citationIDField;
      }
      set
      {
        this.citationIDField = value;
      }
    }

    /// <remarks/>
    public string Jurisdiction
    {
      get
      {
        return this.jurisdictionField;
      }
      set
      {
        this.jurisdictionField = value;
      }
    }

    /// <remarks/>
    public decimal FineAmount
    {
      get
      {
        return this.fineAmountField;
      }
      set
      {
        this.fineAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineAmountSpecified
    {
      get
      {
        return this.fineAmountFieldSpecified;
      }
      set
      {
        this.fineAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseBond Bond
    {
      get
      {
        return this.bondField;
      }
      set
      {
        this.bondField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOffense Offense
    {
      get
      {
        return this.offenseField;
      }
      set
      {
        this.offenseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Bond")]
  public partial class LoadCaseBond
  {

    private string typeField;

    private decimal amountField;

    /// <remarks/>
    public string Type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    public decimal Amount
    {
      get
      {
        return this.amountField;
      }
      set
      {
        this.amountField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Offense")]
  public partial class LoadCaseOffense
  {

    private string codeField;

    private string descriptionField;

    private string degreeField;

    private string statuteField;

    private string gOCField;

    /// <remarks/>
    public string Code
    {
      get
      {
        return this.codeField;
      }
      set
      {
        this.codeField = value;
      }
    }

    /// <remarks/>
    public string Description
    {
      get
      {
        return this.descriptionField;
      }
      set
      {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    public string Degree
    {
      get
      {
        return this.degreeField;
      }
      set
      {
        this.degreeField = value;
      }
    }

    /// <remarks/>
    public string Statute
    {
      get
      {
        return this.statuteField;
      }
      set
      {
        this.statuteField = value;
      }
    }

    /// <remarks/>
    public string GOC
    {
      get
      {
        return this.gOCField;
      }
      set
      {
        this.gOCField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.DispositionFiling")]
  public partial class LoadCaseDispositionFiling
  {

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private string numberField;

    private string jurisdictionField;

    private decimal fineAmountField;

    private bool fineAmountFieldSpecified;

    private LoadCaseBond bondField;

    private LoadCaseOffense offenseField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string Number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    public string Jurisdiction
    {
      get
      {
        return this.jurisdictionField;
      }
      set
      {
        this.jurisdictionField = value;
      }
    }

    /// <remarks/>
    public decimal FineAmount
    {
      get
      {
        return this.fineAmountField;
      }
      set
      {
        this.fineAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineAmountSpecified
    {
      get
      {
        return this.fineAmountFieldSpecified;
      }
      set
      {
        this.fineAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseBond Bond
    {
      get
      {
        return this.bondField;
      }
      set
      {
        this.bondField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOffense Offense
    {
      get
      {
        return this.offenseField;
      }
      set
      {
        this.offenseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.PleaFiling")]
  public partial class LoadCasePleaFiling
  {

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private string numberField;

    private string jurisdictionField;

    private decimal fineAmountField;

    private bool fineAmountFieldSpecified;

    private LoadCaseBond bondField;

    private LoadCaseOffense offenseField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string Number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    public string Jurisdiction
    {
      get
      {
        return this.jurisdictionField;
      }
      set
      {
        this.jurisdictionField = value;
      }
    }

    /// <remarks/>
    public decimal FineAmount
    {
      get
      {
        return this.fineAmountField;
      }
      set
      {
        this.fineAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineAmountSpecified
    {
      get
      {
        return this.fineAmountFieldSpecified;
      }
      set
      {
        this.fineAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseBond Bond
    {
      get
      {
        return this.bondField;
      }
      set
      {
        this.bondField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOffense Offense
    {
      get
      {
        return this.offenseField;
      }
      set
      {
        this.offenseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Amendment")]
  public partial class LoadCaseAmendment
  {

    private string[] reasonsField;

    private string dateField;

    private string commentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reason", IsNullable = false)]
    public string[] Reasons
    {
      get
      {
        return this.reasonsField;
      }
      set
      {
        this.reasonsField = value;
      }
    }

    /// <remarks/>
    public string Date
    {
      get
      {
        return this.dateField;
      }
      set
      {
        this.dateField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.AmendedCaseFiling")]
  public partial class LoadCaseAmendedCaseFiling
  {

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private string numberField;

    private LoadCaseAmendment amendmentField;

    private string jurisdictionField;

    private decimal fineAmountField;

    private bool fineAmountFieldSpecified;

    private LoadCaseBond bondField;

    private string filingDateField;

    private LoadCaseOffense offenseField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string Number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    public LoadCaseAmendment Amendment
    {
      get
      {
        return this.amendmentField;
      }
      set
      {
        this.amendmentField = value;
      }
    }

    /// <remarks/>
    public string Jurisdiction
    {
      get
      {
        return this.jurisdictionField;
      }
      set
      {
        this.jurisdictionField = value;
      }
    }

    /// <remarks/>
    public decimal FineAmount
    {
      get
      {
        return this.fineAmountField;
      }
      set
      {
        this.fineAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineAmountSpecified
    {
      get
      {
        return this.fineAmountFieldSpecified;
      }
      set
      {
        this.fineAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseBond Bond
    {
      get
      {
        return this.bondField;
      }
      set
      {
        this.bondField = value;
      }
    }

    /// <remarks/>
    public string FilingDate
    {
      get
      {
        return this.filingDateField;
      }
      set
      {
        this.filingDateField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOffense Offense
    {
      get
      {
        return this.offenseField;
      }
      set
      {
        this.offenseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseFiling")]
  public partial class LoadCaseCaseFiling
  {

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private string numberField;

    private string jurisdictionField;

    private decimal fineAmountField;

    private bool fineAmountFieldSpecified;

    private LoadCaseBond bondField;

    private string filingDateField;

    private LoadCaseOffense offenseField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string Number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    public string Jurisdiction
    {
      get
      {
        return this.jurisdictionField;
      }
      set
      {
        this.jurisdictionField = value;
      }
    }

    /// <remarks/>
    public decimal FineAmount
    {
      get
      {
        return this.fineAmountField;
      }
      set
      {
        this.fineAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineAmountSpecified
    {
      get
      {
        return this.fineAmountFieldSpecified;
      }
      set
      {
        this.fineAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseBond Bond
    {
      get
      {
        return this.bondField;
      }
      set
      {
        this.bondField = value;
      }
    }

    /// <remarks/>
    public string FilingDate
    {
      get
      {
        return this.filingDateField;
      }
      set
      {
        this.filingDateField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOffense Offense
    {
      get
      {
        return this.offenseField;
      }
      set
      {
        this.offenseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.OfficerFreeText")]
  public partial class LoadCaseOfficerFreeText
  {

    private string badgeNumberField;

    private string nameField;

    /// <remarks/>
    public string BadgeNumber
    {
      get
      {
        return this.badgeNumberField;
      }
      set
      {
        this.badgeNumberField = value;
      }
    }

    /// <remarks/>
    public string Name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.OfficerParty")]
  public partial class LoadCaseOfficerParty
  {

    private string officerIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string OfficerID
    {
      get
      {
        return this.officerIDField;
      }
      set
      {
        this.officerIDField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Officer")]
  public partial class LoadCaseOfficer
  {

    private object itemField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OfficerFreeText", typeof(LoadCaseOfficerFreeText))]
    [System.Xml.Serialization.XmlElementAttribute("OfficerParty", typeof(LoadCaseOfficerParty))]
    public object Item
    {
      get
      {
        return this.itemField;
      }
      set
      {
        this.itemField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.ArrestFiling")]
  public partial class LoadCaseArrestFiling
  {

    private BASEREQUIREDTEXTBOOL isCurrentField;

    private string dateField;

    private string timeField;

    private string arrestControlNumberField;

    private string agencyField;

    private LoadCaseOfficer officerField;

    private string numberField;

    private string jurisdictionField;

    private decimal fineAmountField;

    private bool fineAmountFieldSpecified;

    private LoadCaseBond bondField;

    private LoadCaseOffense offenseField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL IsCurrent
    {
      get
      {
        return this.isCurrentField;
      }
      set
      {
        this.isCurrentField = value;
      }
    }

    /// <remarks/>
    public string Date
    {
      get
      {
        return this.dateField;
      }
      set
      {
        this.dateField = value;
      }
    }

    /// <remarks/>
    public string Time
    {
      get
      {
        return this.timeField;
      }
      set
      {
        this.timeField = value;
      }
    }

    /// <remarks/>
    public string ArrestControlNumber
    {
      get
      {
        return this.arrestControlNumberField;
      }
      set
      {
        this.arrestControlNumberField = value;
      }
    }

    /// <remarks/>
    public string Agency
    {
      get
      {
        return this.agencyField;
      }
      set
      {
        this.agencyField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOfficer Officer
    {
      get
      {
        return this.officerField;
      }
      set
      {
        this.officerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string Number
    {
      get
      {
        return this.numberField;
      }
      set
      {
        this.numberField = value;
      }
    }

    /// <remarks/>
    public string Jurisdiction
    {
      get
      {
        return this.jurisdictionField;
      }
      set
      {
        this.jurisdictionField = value;
      }
    }

    /// <remarks/>
    public decimal FineAmount
    {
      get
      {
        return this.fineAmountField;
      }
      set
      {
        this.fineAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineAmountSpecified
    {
      get
      {
        return this.fineAmountFieldSpecified;
      }
      set
      {
        this.fineAmountFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseBond Bond
    {
      get
      {
        return this.bondField;
      }
      set
      {
        this.bondField = value;
      }
    }

    /// <remarks/>
    public LoadCaseOffense Offense
    {
      get
      {
        return this.offenseField;
      }
      set
      {
        this.offenseField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Vehicle")]
  public partial class LoadCaseVehicle
  {

    private string licensePlateNumberField;

    private string licensePlateStateField;

    /// <remarks/>
    public string LicensePlateNumber
    {
      get
      {
        return this.licensePlateNumberField;
      }
      set
      {
        this.licensePlateNumberField = value;
      }
    }

    /// <remarks/>
    public string LicensePlateState
    {
      get
      {
        return this.licensePlateStateField;
      }
      set
      {
        this.licensePlateStateField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Charge")]
  public partial class LoadCaseCharge
  {

    private string partyIDField;

    private string chargeIDField;

    private string offenseDateField;

    private string offenseDateToField;

    private BASEREQUIREDTEXTBOOL offenseDateOnOrAboutField;

    private string offenseTimeField;

    private string offenseTimeToField;

    private BASEREQUIREDTEXTBOOL offenseTimeAtOrAboutField;

    private string prosecutingAgencyField;

    private string chargeTrackNumberField;

    private string chargeTrackSequenceField;

    private LoadCaseVehicle vehicleField;

    private LoadCaseArrestFiling[] arrestFilingField;

    private LoadCaseCaseFiling[] caseFilingField;

    private LoadCaseAmendedCaseFiling[] amendedCaseFilingField;

    private LoadCasePleaFiling[] pleaFilingField;

    private LoadCaseDispositionFiling[] dispositionFilingField;

    private LoadCaseCitiationFiling[] citiationFilingField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string PartyID
    {
      get
      {
        return this.partyIDField;
      }
      set
      {
        this.partyIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string ChargeID
    {
      get
      {
        return this.chargeIDField;
      }
      set
      {
        this.chargeIDField = value;
      }
    }

    /// <remarks/>
    public string OffenseDate
    {
      get
      {
        return this.offenseDateField;
      }
      set
      {
        this.offenseDateField = value;
      }
    }

    /// <remarks/>
    public string OffenseDateTo
    {
      get
      {
        return this.offenseDateToField;
      }
      set
      {
        this.offenseDateToField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL OffenseDateOnOrAbout
    {
      get
      {
        return this.offenseDateOnOrAboutField;
      }
      set
      {
        this.offenseDateOnOrAboutField = value;
      }
    }

    /// <remarks/>
    public string OffenseTime
    {
      get
      {
        return this.offenseTimeField;
      }
      set
      {
        this.offenseTimeField = value;
      }
    }

    /// <remarks/>
    public string OffenseTimeTo
    {
      get
      {
        return this.offenseTimeToField;
      }
      set
      {
        this.offenseTimeToField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL OffenseTimeAtOrAbout
    {
      get
      {
        return this.offenseTimeAtOrAboutField;
      }
      set
      {
        this.offenseTimeAtOrAboutField = value;
      }
    }

    /// <remarks/>
    public string ProsecutingAgency
    {
      get
      {
        return this.prosecutingAgencyField;
      }
      set
      {
        this.prosecutingAgencyField = value;
      }
    }

    /// <remarks/>
    public string ChargeTrackNumber
    {
      get
      {
        return this.chargeTrackNumberField;
      }
      set
      {
        this.chargeTrackNumberField = value;
      }
    }

    /// <remarks/>
    public string ChargeTrackSequence
    {
      get
      {
        return this.chargeTrackSequenceField;
      }
      set
      {
        this.chargeTrackSequenceField = value;
      }
    }

    /// <remarks/>
    public LoadCaseVehicle Vehicle
    {
      get
      {
        return this.vehicleField;
      }
      set
      {
        this.vehicleField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArrestFiling")]
    public LoadCaseArrestFiling[] ArrestFiling
    {
      get
      {
        return this.arrestFilingField;
      }
      set
      {
        this.arrestFilingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CaseFiling")]
    public LoadCaseCaseFiling[] CaseFiling
    {
      get
      {
        return this.caseFilingField;
      }
      set
      {
        this.caseFilingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmendedCaseFiling")]
    public LoadCaseAmendedCaseFiling[] AmendedCaseFiling
    {
      get
      {
        return this.amendedCaseFilingField;
      }
      set
      {
        this.amendedCaseFilingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PleaFiling")]
    public LoadCasePleaFiling[] PleaFiling
    {
      get
      {
        return this.pleaFilingField;
      }
      set
      {
        this.pleaFilingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DispositionFiling")]
    public LoadCaseDispositionFiling[] DispositionFiling
    {
      get
      {
        return this.dispositionFilingField;
      }
      set
      {
        this.dispositionFilingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CitiationFiling")]
    public LoadCaseCitiationFiling[] CitiationFiling
    {
      get
      {
        return this.citiationFilingField;
      }
      set
      {
        this.citiationFilingField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseEvent")]
  public partial class LoadCaseCaseEvent
  {

    private string eventIDField;

    private string dateField;

    private string typeField;

    private string commentField;

    private BASEREQUIREDTEXTBOOL docketableField;

    private decimal documentIndexNumberField;

    private bool documentIndexNumberFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string EventID
    {
      get
      {
        return this.eventIDField;
      }
      set
      {
        this.eventIDField = value;
      }
    }

    /// <remarks/>
    public string Date
    {
      get
      {
        return this.dateField;
      }
      set
      {
        this.dateField = value;
      }
    }

    /// <remarks/>
    public string Type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL Docketable
    {
      get
      {
        return this.docketableField;
      }
      set
      {
        this.docketableField = value;
      }
    }

    /// <remarks/>
    public decimal DocumentIndexNumber
    {
      get
      {
        return this.documentIndexNumberField;
      }
      set
      {
        this.documentIndexNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DocumentIndexNumberSpecified
    {
      get
      {
        return this.documentIndexNumberFieldSpecified;
      }
      set
      {
        this.documentIndexNumberFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.RepresentedParty")]
  public partial class LoadCaseRepresentedParty
  {

    private string partyIDField;

    private BASEREQUIREDTEXTBOOL leadField;

    private BASEREQUIREDTEXTBOOL courtAppointedField;

    private string judgeField;

    private BASEREQUIREDTEXTBOOL publicDefenderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string PartyID
    {
      get
      {
        return this.partyIDField;
      }
      set
      {
        this.partyIDField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL Lead
    {
      get
      {
        return this.leadField;
      }
      set
      {
        this.leadField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL CourtAppointed
    {
      get
      {
        return this.courtAppointedField;
      }
      set
      {
        this.courtAppointedField = value;
      }
    }

    /// <remarks/>
    public string Judge
    {
      get
      {
        return this.judgeField;
      }
      set
      {
        this.judgeField = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL PublicDefender
    {
      get
      {
        return this.publicDefenderField;
      }
      set
      {
        this.publicDefenderField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.AttorneyConnection")]
  public partial class LoadCaseAttorneyConnection
  {

    private string connectionTypeField;

    private string addDateField;

    private string removeDateField;

    private string removeReasonField;

    private string commentField;

    private LoadCaseRepresentedParty representedPartyField;

    /// <remarks/>
    public string ConnectionType
    {
      get
      {
        return this.connectionTypeField;
      }
      set
      {
        this.connectionTypeField = value;
      }
    }

    /// <remarks/>
    public string AddDate
    {
      get
      {
        return this.addDateField;
      }
      set
      {
        this.addDateField = value;
      }
    }

    /// <remarks/>
    public string RemoveDate
    {
      get
      {
        return this.removeDateField;
      }
      set
      {
        this.removeDateField = value;
      }
    }

    /// <remarks/>
    public string RemoveReason
    {
      get
      {
        return this.removeReasonField;
      }
      set
      {
        this.removeReasonField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }

    /// <remarks/>
    public LoadCaseRepresentedParty RepresentedParty
    {
      get
      {
        return this.representedPartyField;
      }
      set
      {
        this.representedPartyField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Attorney")]
  public partial class LoadCaseAttorney
  {

    private string attorneyIDField;

    private string barNumberField;

    private LoadCaseAttorneyConnection[] connectionsField;

    private LoadCaseNames namesField;

    private LoadCaseAddresses addressesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string AttorneyID
    {
      get
      {
        return this.attorneyIDField;
      }
      set
      {
        this.attorneyIDField = value;
      }
    }

    /// <remarks/>
    public string BarNumber
    {
      get
      {
        return this.barNumberField;
      }
      set
      {
        this.barNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Connection", IsNullable = false)]
    public LoadCaseAttorneyConnection[] Connections
    {
      get
      {
        return this.connectionsField;
      }
      set
      {
        this.connectionsField = value;
      }
    }

    /// <remarks/>
    public LoadCaseNames Names
    {
      get
      {
        return this.namesField;
      }
      set
      {
        this.namesField = value;
      }
    }

    /// <remarks/>
    public LoadCaseAddresses Addresses
    {
      get
      {
        return this.addressesField;
      }
      set
      {
        this.addressesField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Names")]
  public partial class LoadCaseNames
  {

    private JusticePartyName primaryNameField;

    private LoadCaseName[] nameField;

    /// <remarks/>
    public JusticePartyName PrimaryName
    {
      get
      {
        return this.primaryNameField;
      }
      set
      {
        this.primaryNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name")]
    public LoadCaseName[] Name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Justice.Party.Name")]
  public partial class JusticePartyName
  {

    private object itemField;

    private string currentKnownField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Business", typeof(JusticePartyBusiness))]
    [System.Xml.Serialization.XmlElementAttribute("Nickname", typeof(JusticePartyNickname))]
    [System.Xml.Serialization.XmlElementAttribute("Person", typeof(JusticePartyPerson))]
    public object Item
    {
      get
      {
        return this.itemField;
      }
      set
      {
        this.itemField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CurrentKnown
    {
      get
      {
        return this.currentKnownField;
      }
      set
      {
        this.currentKnownField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Justice.Party.Business")]
  public partial class JusticePartyBusiness
  {

    private string businessNameField;

    /// <remarks/>
    public string BusinessName
    {
      get
      {
        return this.businessNameField;
      }
      set
      {
        this.businessNameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Justice.Party.Nickname")]
  public partial class JusticePartyNickname
  {

    private string partyNicknameField;

    /// <remarks/>
    public string PartyNickname
    {
      get
      {
        return this.partyNicknameField;
      }
      set
      {
        this.partyNicknameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Justice.Party.Person")]
  public partial class JusticePartyPerson
  {

    private BASENAMETITLECODE titleField;

    private bool titleFieldSpecified;

    private string firstField;

    private string middleField;

    private string lastField;

    private string suffixField;

    /// <remarks/>
    public BASENAMETITLECODE Title
    {
      get
      {
        return this.titleField;
      }
      set
      {
        this.titleField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TitleSpecified
    {
      get
      {
        return this.titleFieldSpecified;
      }
      set
      {
        this.titleFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string First
    {
      get
      {
        return this.firstField;
      }
      set
      {
        this.firstField = value;
      }
    }

    /// <remarks/>
    public string Middle
    {
      get
      {
        return this.middleField;
      }
      set
      {
        this.middleField = value;
      }
    }

    /// <remarks/>
    public string Last
    {
      get
      {
        return this.lastField;
      }
      set
      {
        this.lastField = value;
      }
    }

    /// <remarks/>
    public string Suffix
    {
      get
      {
        return this.suffixField;
      }
      set
      {
        this.suffixField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.NAMETITLE.CODE")]
  public enum BASENAMETITLECODE
  {

    /// <remarks/>
    Agt,

    /// <remarks/>
    Dep,

    /// <remarks/>
    Det,

    /// <remarks/>
    Dr,

    /// <remarks/>
    Hon,

    /// <remarks/>
    Miss,

    /// <remarks/>
    Mr,

    /// <remarks/>
    Mrs,

    /// <remarks/>
    Ms,

    /// <remarks/>
    Off,

    /// <remarks/>
    Rev,

    /// <remarks/>
    Tpr,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Name")]
  public partial class LoadCaseName
  {

    private string partyNameTypeField;

    private object itemField;

    /// <remarks/>
    public string PartyNameType
    {
      get
      {
        return this.partyNameTypeField;
      }
      set
      {
        this.partyNameTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Business", typeof(JusticePartyBusiness))]
    [System.Xml.Serialization.XmlElementAttribute("NickName", typeof(JusticePartyNickname))]
    [System.Xml.Serialization.XmlElementAttribute("Person", typeof(JusticePartyPerson))]
    public object Item
    {
      get
      {
        return this.itemField;
      }
      set
      {
        this.itemField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Addresses")]
  public partial class LoadCaseAddresses
  {

    private LoadCaseResultPartyAddress caseCorrespondenceField;

    private LoadCaseResultPartyAddress partyCorrespondenceField;

    /// <remarks/>
    public LoadCaseResultPartyAddress CaseCorrespondence
    {
      get
      {
        return this.caseCorrespondenceField;
      }
      set
      {
        this.caseCorrespondenceField = value;
      }
    }

    /// <remarks/>
    public LoadCaseResultPartyAddress PartyCorrespondence
    {
      get
      {
        return this.partyCorrespondenceField;
      }
      set
      {
        this.partyCorrespondenceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCaseResult.Party.Address")]
  public partial class LoadCaseResultPartyAddress
  {

    private object itemField;

    private JusticePartyAddressAddressFlags addressFlagsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Foreign", typeof(BASEFOREIGN))]
    [System.Xml.Serialization.XmlElementAttribute("NonStandardUS", typeof(BASENONSTANDARDUS))]
    [System.Xml.Serialization.XmlElementAttribute("StandardUS", typeof(LoadCaseResultStandardUS))]
    [System.Xml.Serialization.XmlElementAttribute("StandardUSwithAttn", typeof(LoadCaseResultStandardUSWithAttn))]
    public object Item
    {
      get
      {
        return this.itemField;
      }
      set
      {
        this.itemField = value;
      }
    }

    /// <remarks/>
    public JusticePartyAddressAddressFlags AddressFlags
    {
      get
      {
        return this.addressFlagsField;
      }
      set
      {
        this.addressFlagsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.FOREIGN")]
  public partial class BASEFOREIGN
  {

    private string line1Field;

    private string line2Field;

    private string line3Field;

    private string line4Field;

    /// <remarks/>
    public string Line1
    {
      get
      {
        return this.line1Field;
      }
      set
      {
        this.line1Field = value;
      }
    }

    /// <remarks/>
    public string Line2
    {
      get
      {
        return this.line2Field;
      }
      set
      {
        this.line2Field = value;
      }
    }

    /// <remarks/>
    public string Line3
    {
      get
      {
        return this.line3Field;
      }
      set
      {
        this.line3Field = value;
      }
    }

    /// <remarks/>
    public string Line4
    {
      get
      {
        return this.line4Field;
      }
      set
      {
        this.line4Field = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.NONSTANDARDUS")]
  public partial class BASENONSTANDARDUS
  {

    private string line1Field;

    private string line2Field;

    private string line3Field;

    private string cityField;

    private BASESTATECODE stateField;

    private string zipField;

    /// <remarks/>
    public string Line1
    {
      get
      {
        return this.line1Field;
      }
      set
      {
        this.line1Field = value;
      }
    }

    /// <remarks/>
    public string Line2
    {
      get
      {
        return this.line2Field;
      }
      set
      {
        this.line2Field = value;
      }
    }

    /// <remarks/>
    public string Line3
    {
      get
      {
        return this.line3Field;
      }
      set
      {
        this.line3Field = value;
      }
    }

    /// <remarks/>
    public string City
    {
      get
      {
        return this.cityField;
      }
      set
      {
        this.cityField = value;
      }
    }

    /// <remarks/>
    public BASESTATECODE State
    {
      get
      {
        return this.stateField;
      }
      set
      {
        this.stateField = value;
      }
    }

    /// <remarks/>
    public string Zip
    {
      get
      {
        return this.zipField;
      }
      set
      {
        this.zipField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.STATE.CODE")]
  public enum BASESTATECODE
  {

    /// <remarks/>
    AA,

    /// <remarks/>
    AE,

    /// <remarks/>
    AK,

    /// <remarks/>
    AL,

    /// <remarks/>
    AP,

    /// <remarks/>
    AR,

    /// <remarks/>
    AS,

    /// <remarks/>
    AZ,

    /// <remarks/>
    CA,

    /// <remarks/>
    CD,

    /// <remarks/>
    CO,

    /// <remarks/>
    CT,

    /// <remarks/>
    DC,

    /// <remarks/>
    DE,

    /// <remarks/>
    FL,

    /// <remarks/>
    FM,

    /// <remarks/>
    GA,

    /// <remarks/>
    GU,

    /// <remarks/>
    HI,

    /// <remarks/>
    IA,

    /// <remarks/>
    ID,

    /// <remarks/>
    IL,

    /// <remarks/>
    IN,

    /// <remarks/>
    KS,

    /// <remarks/>
    KY,

    /// <remarks/>
    LA,

    /// <remarks/>
    MA,

    /// <remarks/>
    MD,

    /// <remarks/>
    ME,

    /// <remarks/>
    MH,

    /// <remarks/>
    MI,

    /// <remarks/>
    MM,

    /// <remarks/>
    MN,

    /// <remarks/>
    MO,

    /// <remarks/>
    MP,

    /// <remarks/>
    MS,

    /// <remarks/>
    MT,

    /// <remarks/>
    MX,

    /// <remarks/>
    NC,

    /// <remarks/>
    ND,

    /// <remarks/>
    NE,

    /// <remarks/>
    NH,

    /// <remarks/>
    NJ,

    /// <remarks/>
    NM,

    /// <remarks/>
    NV,

    /// <remarks/>
    NY,

    /// <remarks/>
    OA,

    /// <remarks/>
    OH,

    /// <remarks/>
    OK,

    /// <remarks/>
    OR,

    /// <remarks/>
    PA,

    /// <remarks/>
    PR,

    /// <remarks/>
    RI,

    /// <remarks/>
    SC,

    /// <remarks/>
    SD,

    /// <remarks/>
    TN,

    /// <remarks/>
    TX,

    /// <remarks/>
    UT,

    /// <remarks/>
    VA,

    /// <remarks/>
    VI,

    /// <remarks/>
    VT,

    /// <remarks/>
    WA,

    /// <remarks/>
    WI,

    /// <remarks/>
    WV,

    /// <remarks/>
    WY,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCaseResult.StandardUS")]
  public partial class LoadCaseResultStandardUS
  {

    private string streetNumberField;

    private BASEDIRECTIONCODE preDirectionField;

    private bool preDirectionFieldSpecified;

    private string streetNameField;

    private BASERDSUFFIXCODE streetTypeField;

    private bool streetTypeFieldSpecified;

    private BASEDIRECTIONCODE postDirectionField;

    private bool postDirectionFieldSpecified;

    private LoadCaseResultUnit unitField;

    private string cityField;

    private BASESTATECODE stateField;

    private string zipField;

    /// <remarks/>
    public string StreetNumber
    {
      get
      {
        return this.streetNumberField;
      }
      set
      {
        this.streetNumberField = value;
      }
    }

    /// <remarks/>
    public BASEDIRECTIONCODE PreDirection
    {
      get
      {
        return this.preDirectionField;
      }
      set
      {
        this.preDirectionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreDirectionSpecified
    {
      get
      {
        return this.preDirectionFieldSpecified;
      }
      set
      {
        this.preDirectionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string StreetName
    {
      get
      {
        return this.streetNameField;
      }
      set
      {
        this.streetNameField = value;
      }
    }

    /// <remarks/>
    public BASERDSUFFIXCODE StreetType
    {
      get
      {
        return this.streetTypeField;
      }
      set
      {
        this.streetTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StreetTypeSpecified
    {
      get
      {
        return this.streetTypeFieldSpecified;
      }
      set
      {
        this.streetTypeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public BASEDIRECTIONCODE PostDirection
    {
      get
      {
        return this.postDirectionField;
      }
      set
      {
        this.postDirectionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostDirectionSpecified
    {
      get
      {
        return this.postDirectionFieldSpecified;
      }
      set
      {
        this.postDirectionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseResultUnit Unit
    {
      get
      {
        return this.unitField;
      }
      set
      {
        this.unitField = value;
      }
    }

    /// <remarks/>
    public string City
    {
      get
      {
        return this.cityField;
      }
      set
      {
        this.cityField = value;
      }
    }

    /// <remarks/>
    public BASESTATECODE State
    {
      get
      {
        return this.stateField;
      }
      set
      {
        this.stateField = value;
      }
    }

    /// <remarks/>
    public string Zip
    {
      get
      {
        return this.zipField;
      }
      set
      {
        this.zipField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.DIRECTION.CODE")]
  public enum BASEDIRECTIONCODE
  {

    /// <remarks/>
    E,

    /// <remarks/>
    N,

    /// <remarks/>
    NE,

    /// <remarks/>
    NW,

    /// <remarks/>
    S,

    /// <remarks/>
    SE,

    /// <remarks/>
    SW,

    /// <remarks/>
    W,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.RDSUFFIX.CODE")]
  public enum BASERDSUFFIXCODE
  {

    /// <remarks/>
    ALY,

    /// <remarks/>
    ANX,

    /// <remarks/>
    ARC,

    /// <remarks/>
    AVE,

    /// <remarks/>
    BYU,

    /// <remarks/>
    BCH,

    /// <remarks/>
    BND,

    /// <remarks/>
    BLF,

    /// <remarks/>
    BLFS,

    /// <remarks/>
    BTM,

    /// <remarks/>
    BLVD,

    /// <remarks/>
    BR,

    /// <remarks/>
    BRG,

    /// <remarks/>
    BRK,

    /// <remarks/>
    BRKS,

    /// <remarks/>
    BG,

    /// <remarks/>
    BGS,

    /// <remarks/>
    BYP,

    /// <remarks/>
    CP,

    /// <remarks/>
    CYN,

    /// <remarks/>
    CPE,

    /// <remarks/>
    CSWY,

    /// <remarks/>
    CTR,

    /// <remarks/>
    CTRS,

    /// <remarks/>
    CIR,

    /// <remarks/>
    CIRS,

    /// <remarks/>
    CLF,

    /// <remarks/>
    CLFS,

    /// <remarks/>
    CLB,

    /// <remarks/>
    CMN,

    /// <remarks/>
    CONN,

    /// <remarks/>
    COR,

    /// <remarks/>
    CORS,

    /// <remarks/>
    CRSE,

    /// <remarks/>
    CT,

    /// <remarks/>
    CTS,

    /// <remarks/>
    CV,

    /// <remarks/>
    CVS,

    /// <remarks/>
    CRK,

    /// <remarks/>
    CRES,

    /// <remarks/>
    CRST,

    /// <remarks/>
    XING,

    /// <remarks/>
    XRD,

    /// <remarks/>
    CURV,

    /// <remarks/>
    DL,

    /// <remarks/>
    DM,

    /// <remarks/>
    DV,

    /// <remarks/>
    DR,

    /// <remarks/>
    DRS,

    /// <remarks/>
    EST,

    /// <remarks/>
    ESTS,

    /// <remarks/>
    EXPY,

    /// <remarks/>
    EXT,

    /// <remarks/>
    EXTS,

    /// <remarks/>
    FALL,

    /// <remarks/>
    FLS,

    /// <remarks/>
    FRY,

    /// <remarks/>
    FLD,

    /// <remarks/>
    FLDS,

    /// <remarks/>
    FLT,

    /// <remarks/>
    FLTS,

    /// <remarks/>
    FRD,

    /// <remarks/>
    FRDS,

    /// <remarks/>
    FRST,

    /// <remarks/>
    FRG,

    /// <remarks/>
    FRGS,

    /// <remarks/>
    FRK,

    /// <remarks/>
    FRKS,

    /// <remarks/>
    FT,

    /// <remarks/>
    FWY,

    /// <remarks/>
    GDN,

    /// <remarks/>
    GDNS,

    /// <remarks/>
    GTWY,

    /// <remarks/>
    GLN,

    /// <remarks/>
    GLNS,

    /// <remarks/>
    GRN,

    /// <remarks/>
    GRNS,

    /// <remarks/>
    GRV,

    /// <remarks/>
    GRVS,

    /// <remarks/>
    HBR,

    /// <remarks/>
    HBRS,

    /// <remarks/>
    HVN,

    /// <remarks/>
    HTS,

    /// <remarks/>
    HWY,

    /// <remarks/>
    HL,

    /// <remarks/>
    HLS,

    /// <remarks/>
    HOLW,

    /// <remarks/>
    INLT,

    /// <remarks/>
    IS,

    /// <remarks/>
    ISS,

    /// <remarks/>
    ISLE,

    /// <remarks/>
    JCT,

    /// <remarks/>
    JCTS,

    /// <remarks/>
    KY,

    /// <remarks/>
    KYS,

    /// <remarks/>
    KNL,

    /// <remarks/>
    KNLS,

    /// <remarks/>
    LK,

    /// <remarks/>
    LKS,

    /// <remarks/>
    LAND,

    /// <remarks/>
    LNDG,

    /// <remarks/>
    LN,

    /// <remarks/>
    LGT,

    /// <remarks/>
    LGTS,

    /// <remarks/>
    LF,

    /// <remarks/>
    LCK,

    /// <remarks/>
    LCKS,

    /// <remarks/>
    LDG,

    /// <remarks/>
    LOOP,

    /// <remarks/>
    MALL,

    /// <remarks/>
    MNR,

    /// <remarks/>
    MNRS,

    /// <remarks/>
    MDW,

    /// <remarks/>
    MDWS,

    /// <remarks/>
    MEWS,

    /// <remarks/>
    ML,

    /// <remarks/>
    MTWY,

    /// <remarks/>
    MLS,

    /// <remarks/>
    MSN,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("MTWY")]
    MTWY1,

    /// <remarks/>
    MT,

    /// <remarks/>
    MTN,

    /// <remarks/>
    MTNS,

    /// <remarks/>
    NCK,

    /// <remarks/>
    ORCH,

    /// <remarks/>
    OVAL,

    /// <remarks/>
    OPAS,

    /// <remarks/>
    PARK,

    /// <remarks/>
    PKWY,

    /// <remarks/>
    PASS,

    /// <remarks/>
    PSGE,

    /// <remarks/>
    PATH,

    /// <remarks/>
    PIKE,

    /// <remarks/>
    PNE,

    /// <remarks/>
    PNES,

    /// <remarks/>
    PL,

    /// <remarks/>
    PLN,

    /// <remarks/>
    PLNS,

    /// <remarks/>
    PLZ,

    /// <remarks/>
    PT,

    /// <remarks/>
    PTS,

    /// <remarks/>
    PRT,

    /// <remarks/>
    PRTS,

    /// <remarks/>
    PR,

    /// <remarks/>
    RADL,

    /// <remarks/>
    RAMP,

    /// <remarks/>
    RNCH,

    /// <remarks/>
    RPD,

    /// <remarks/>
    RPDS,

    /// <remarks/>
    RST,

    /// <remarks/>
    RDG,

    /// <remarks/>
    RDGS,

    /// <remarks/>
    RIV,

    /// <remarks/>
    RD,

    /// <remarks/>
    RDS,

    /// <remarks/>
    RTE,

    /// <remarks/>
    ROW,

    /// <remarks/>
    RUE,

    /// <remarks/>
    RUN,

    /// <remarks/>
    SHL,

    /// <remarks/>
    SHLS,

    /// <remarks/>
    SHR,

    /// <remarks/>
    SHRS,

    /// <remarks/>
    SKWY,

    /// <remarks/>
    SPG,

    /// <remarks/>
    SPGS,

    /// <remarks/>
    SPUR,

    /// <remarks/>
    SQ,

    /// <remarks/>
    SQS,

    /// <remarks/>
    STA,

    /// <remarks/>
    STRA,

    /// <remarks/>
    STRM,

    /// <remarks/>
    ST,

    /// <remarks/>
    STS,

    /// <remarks/>
    SMT,

    /// <remarks/>
    TER,

    /// <remarks/>
    TRWY,

    /// <remarks/>
    TRCE,

    /// <remarks/>
    TRAK,

    /// <remarks/>
    TRFY,

    /// <remarks/>
    TRL,

    /// <remarks/>
    TUNL,

    /// <remarks/>
    TPKE,

    /// <remarks/>
    UPAS,

    /// <remarks/>
    UN,

    /// <remarks/>
    UNS,

    /// <remarks/>
    VLY,

    /// <remarks/>
    VLYS,

    /// <remarks/>
    VIA,

    /// <remarks/>
    VW,

    /// <remarks/>
    VWS,

    /// <remarks/>
    VLG,

    /// <remarks/>
    VLGS,

    /// <remarks/>
    VL,

    /// <remarks/>
    VIS,

    /// <remarks/>
    WALK,

    /// <remarks/>
    WALL,

    /// <remarks/>
    WAY,

    /// <remarks/>
    WAYS,

    /// <remarks/>
    WL,

    /// <remarks/>
    WLS,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCaseResult.Unit")]
  public partial class LoadCaseResultUnit
  {

    private BASEUNITTYPECODE unitTypeField;

    private bool unitTypeFieldSpecified;

    private string unitNumberField;

    /// <remarks/>
    public BASEUNITTYPECODE UnitType
    {
      get
      {
        return this.unitTypeField;
      }
      set
      {
        this.unitTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitTypeSpecified
    {
      get
      {
        return this.unitTypeFieldSpecified;
      }
      set
      {
        this.unitTypeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string UnitNumber
    {
      get
      {
        return this.unitNumberField;
      }
      set
      {
        this.unitNumberField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.UNITTYPE.CODE")]
  public enum BASEUNITTYPECODE
  {

    /// <remarks/>
    APT,

    /// <remarks/>
    BLDG,

    /// <remarks/>
    DEPT,

    /// <remarks/>
    FL,

    /// <remarks/>
    LOT,

    /// <remarks/>
    RM,

    /// <remarks/>
    STE,

    /// <remarks/>
    TRLR,

    /// <remarks/>
    UNIT,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCaseResult.StandardUSWithAttn")]
  public partial class LoadCaseResultStandardUSWithAttn
  {

    private string attentionField;

    private string streetNumberField;

    private BASEDIRECTIONCODE preDirectionField;

    private bool preDirectionFieldSpecified;

    private string streetNameField;

    private BASERDSUFFIXCODE streetTypeField;

    private bool streetTypeFieldSpecified;

    private BASEDIRECTIONCODE postDirectionField;

    private bool postDirectionFieldSpecified;

    private LoadCaseResultUnit unitField;

    private string cityField;

    private BASESTATECODE stateField;

    private string zipField;

    /// <remarks/>
    public string Attention
    {
      get
      {
        return this.attentionField;
      }
      set
      {
        this.attentionField = value;
      }
    }

    /// <remarks/>
    public string StreetNumber
    {
      get
      {
        return this.streetNumberField;
      }
      set
      {
        this.streetNumberField = value;
      }
    }

    /// <remarks/>
    public BASEDIRECTIONCODE PreDirection
    {
      get
      {
        return this.preDirectionField;
      }
      set
      {
        this.preDirectionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreDirectionSpecified
    {
      get
      {
        return this.preDirectionFieldSpecified;
      }
      set
      {
        this.preDirectionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string StreetName
    {
      get
      {
        return this.streetNameField;
      }
      set
      {
        this.streetNameField = value;
      }
    }

    /// <remarks/>
    public BASERDSUFFIXCODE StreetType
    {
      get
      {
        return this.streetTypeField;
      }
      set
      {
        this.streetTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StreetTypeSpecified
    {
      get
      {
        return this.streetTypeFieldSpecified;
      }
      set
      {
        this.streetTypeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public BASEDIRECTIONCODE PostDirection
    {
      get
      {
        return this.postDirectionField;
      }
      set
      {
        this.postDirectionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostDirectionSpecified
    {
      get
      {
        return this.postDirectionFieldSpecified;
      }
      set
      {
        this.postDirectionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public LoadCaseResultUnit Unit
    {
      get
      {
        return this.unitField;
      }
      set
      {
        this.unitField = value;
      }
    }

    /// <remarks/>
    public string City
    {
      get
      {
        return this.cityField;
      }
      set
      {
        this.cityField = value;
      }
    }

    /// <remarks/>
    public BASESTATECODE State
    {
      get
      {
        return this.stateField;
      }
      set
      {
        this.stateField = value;
      }
    }

    /// <remarks/>
    public string Zip
    {
      get
      {
        return this.zipField;
      }
      set
      {
        this.zipField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Justice.Party.Address.AddressFlags")]
  public partial class JusticePartyAddressAddressFlags
  {

    private BASEREQUIREDTEXTBOOL correspondenceField;

    private bool correspondenceFieldSpecified;

    private BASEREQUIREDTEXTBOOL undeliverableField;

    private bool undeliverableFieldSpecified;

    private BASEREQUIREDTEXTBOOL confidentialField;

    private bool confidentialFieldSpecified;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL Correspondence
    {
      get
      {
        return this.correspondenceField;
      }
      set
      {
        this.correspondenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CorrespondenceSpecified
    {
      get
      {
        return this.correspondenceFieldSpecified;
      }
      set
      {
        this.correspondenceFieldSpecified = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL Undeliverable
    {
      get
      {
        return this.undeliverableField;
      }
      set
      {
        this.undeliverableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UndeliverableSpecified
    {
      get
      {
        return this.undeliverableFieldSpecified;
      }
      set
      {
        this.undeliverableFieldSpecified = value;
      }
    }

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL Confidential
    {
      get
      {
        return this.confidentialField;
      }
      set
      {
        this.confidentialField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfidentialSpecified
    {
      get
      {
        return this.confidentialFieldSpecified;
      }
      set
      {
        this.confidentialFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.ProSe")]
  public partial class LoadCaseProSe
  {

    private BASEREQUIREDTEXTBOOL leadField;

    private string addDateField;

    private string removeDateField;

    private string removeReasonField;

    private string commentField;

    /// <remarks/>
    public BASEREQUIREDTEXTBOOL Lead
    {
      get
      {
        return this.leadField;
      }
      set
      {
        this.leadField = value;
      }
    }

    /// <remarks/>
    public string AddDate
    {
      get
      {
        return this.addDateField;
      }
      set
      {
        this.addDateField = value;
      }
    }

    /// <remarks/>
    public string RemoveDate
    {
      get
      {
        return this.removeDateField;
      }
      set
      {
        this.removeDateField = value;
      }
    }

    /// <remarks/>
    public string RemoveReason
    {
      get
      {
        return this.removeReasonField;
      }
      set
      {
        this.removeReasonField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Connection")]
  public partial class LoadCaseConnection
  {

    private string connectionTypeField;

    private string partyParticipantField;

    private string addDateField;

    private string removeDateField;

    private string removeReasonField;

    private string commentField;

    /// <remarks/>
    public string ConnectionType
    {
      get
      {
        return this.connectionTypeField;
      }
      set
      {
        this.connectionTypeField = value;
      }
    }

    /// <remarks/>
    public string PartyParticipant
    {
      get
      {
        return this.partyParticipantField;
      }
      set
      {
        this.partyParticipantField = value;
      }
    }

    /// <remarks/>
    public string AddDate
    {
      get
      {
        return this.addDateField;
      }
      set
      {
        this.addDateField = value;
      }
    }

    /// <remarks/>
    public string RemoveDate
    {
      get
      {
        return this.removeDateField;
      }
      set
      {
        this.removeDateField = value;
      }
    }

    /// <remarks/>
    public string RemoveReason
    {
      get
      {
        return this.removeReasonField;
      }
      set
      {
        this.removeReasonField = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseParty")]
  public partial class LoadCaseCaseParty
  {

    private string partyIDField;

    private LoadCaseConnection[] connectionsField;

    private LoadCaseProSe proSeField;

    private LoadCaseNames namesField;

    private LoadCaseAddresses addressesField;

    private LoadCaseNotice noticeField;

    private bool noticeFieldSpecified;

    private string partyStyleField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string PartyID
    {
      get
      {
        return this.partyIDField;
      }
      set
      {
        this.partyIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Connection", IsNullable = false)]
    public LoadCaseConnection[] Connections
    {
      get
      {
        return this.connectionsField;
      }
      set
      {
        this.connectionsField = value;
      }
    }

    /// <remarks/>
    public LoadCaseProSe ProSe
    {
      get
      {
        return this.proSeField;
      }
      set
      {
        this.proSeField = value;
      }
    }

    /// <remarks/>
    public LoadCaseNames Names
    {
      get
      {
        return this.namesField;
      }
      set
      {
        this.namesField = value;
      }
    }

    /// <remarks/>
    public LoadCaseAddresses Addresses
    {
      get
      {
        return this.addressesField;
      }
      set
      {
        this.addressesField = value;
      }
    }

    /// <remarks/>
    public LoadCaseNotice Notice
    {
      get
      {
        return this.noticeField;
      }
      set
      {
        this.noticeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NoticeSpecified
    {
      get
      {
        return this.noticeFieldSpecified;
      }
      set
      {
        this.noticeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string PartyStyle
    {
      get
      {
        return this.partyStyleField;
      }
      set
      {
        this.partyStyleField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.Notice")]
  public enum LoadCaseNotice
  {

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Do Not Send")]
    DoNotSend,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Always Send")]
    AlwaysSend,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LoadCase.CaseParties")]
  public partial class LoadCaseCaseParties
  {

    private LoadCaseCaseParty[] casePartyField;

    private LoadCaseAttorney[] attorneyField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CaseParty")]
    public LoadCaseCaseParty[] CaseParty
    {
      get
      {
        return this.casePartyField;
      }
      set
      {
        this.casePartyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attorney")]
    public LoadCaseAttorney[] Attorney
    {
      get
      {
        return this.attorneyField;
      }
      set
      {
        this.attorneyField = value;
      }
    }
  }
}
