//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ILCookTKIDSInboundFileJob.Entities
{
  using System.Xml.Serialization;
  using Tyler.Odyssey.API.Shared;

  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Message", IsNullable = false)]
  public partial class LoadCaseEntity : BaseGeneratedAPIEntity
  {

    private string caseIDField;

    private LoadEntitiesCollection loadEntitiesField;

    private LOCALLOADCASE messageTypeField;

    //private string nodeIDField;

    //private string referenceNumberField;

    //private string userIDField;

    //private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CaseID
    {
      get
      {
        return this.caseIDField;
      }
      set
      {
        this.caseIDField = value;
      }
    }

    /// <remarks/>
    public LoadEntitiesCollection LoadEntities
    {
      get
      {
        return this.loadEntitiesField;
      }
      set
      {
        this.loadEntitiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LOCALLOADCASE MessageType
    {
      get
      {
        return this.messageTypeField;
      }
      set
      {
        this.messageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferenceNumber
    {
      get
      {
        return this.referenceNumberField;
      }
      set
      {
        this.referenceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class LoadEntitiesCollection
  {

    private string casePartiesField;

    private string caseEventsField;

    private string caseStatusesField;

    private string chargesField;

    private string causesOfActionField;

    private string caseCrossReferencesField;

    private string caseFlagsField;

    private string caseInterimPlacementsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CaseParties
    {
      get
      {
        return this.casePartiesField;
      }
      set
      {
        this.casePartiesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CaseEvents
    {
      get
      {
        return this.caseEventsField;
      }
      set
      {
        this.caseEventsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CaseStatuses
    {
      get
      {
        return this.caseStatusesField;
      }
      set
      {
        this.caseStatusesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string Charges
    {
      get
      {
        return this.chargesField;
      }
      set
      {
        this.chargesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CausesOfAction
    {
      get
      {
        return this.causesOfActionField;
      }
      set
      {
        this.causesOfActionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CaseCrossReferences
    {
      get
      {
        return this.caseCrossReferencesField;
      }
      set
      {
        this.caseCrossReferencesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CaseFlags
    {
      get
      {
        return this.caseFlagsField;
      }
      set
      {
        this.caseFlagsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string CaseInterimPlacements
    {
      get
      {
        return this.caseInterimPlacementsField;
      }
      set
      {
        this.caseInterimPlacementsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOCAL.LOADCASE")]
  public enum LOCALLOADCASE
  {

    /// <remarks/>
    LoadCase,
  }
}
